apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: python-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: acrdevsample2024.azurecr.io/app:latest
        ports:
          - containerPort: 443
        env:
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb.secretName }}
                key: mongodb-connection-string
