apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  # connection_string: {{ .Values.secret.connection_string | b64enc | quote }}
  connection_string: {{ .Values.secret.connection_string }}