name: Update Azure Infra

on:
  workflow_dispatch:
    inputs:
      terraform-choice:
        type: choice
        description: Select the action for the infra
        options:
        - create/update
        - destroy
      env-choice:
        type: choice
        description: Select the Environment
        options:
        - dev
        - stage
        - prod
    # secrets:
    #   AZURE_CREDENTIALS:
    #     required: true

env:
  tf_version: '1.7.4'
  tf_working_dir: 'iac/terraform/envs/${{ inputs.env-choice }}'
  env: 'dev'

permissions:
      id-token: write
      contents: read  

jobs:
  update-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.tf_version }}

      - name: Login to Azure
        uses: azure/login@v1.5.1
        with:
          creds: ${{ secrets[format('{0}_AZURE_CREDENTIALS', inputs.env-choice)] }}

      - name: 'terraform init'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform init

      - name: 'terraform plan'
        if: inputs.terraform-choice == 'create'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform plan -out=tfplan -var-file=${{ inputs.env-choice }}.tfvars

      - name: 'terraform apply'
        if: inputs.terraform-choice == 'create'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform apply tfplan -auto-approve

      - name: 'terraform destroy-all'
        if: inputs.terraform-choice == 'destroy'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform destroy -auto-approve
