name: Update Azure Infra

on:
  workflow_dispatch:
    inputs:
      terraform-choice:
        type: choice
        description: Select the action for the infra
        options:
        - create/update
        - destroy
    secrets:
      aws_account:
        required: true

env:
  tf_version: '1.7.3'
  tf_working_dir: 'iac/terraform/'
  env: 'dev'
  aws_region: 'us-east-1'

permissions:
      id-token: write
      contents: read  

jobs:
  update-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.tf_version }}

      - name: 'terraform init'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform init

      - name: 'terraform apply'
        if: inputs.terraform-choice == 'create'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform apply -auto-approve

      - name: 'terraform destroy-all'
        if: inputs.terraform-choice == 'destroy'
        working-directory: ${{ env.tf_working_dir }}
        run: |
          terraform destroy -auto-approve
